### PR TITLE
Provide reasoning for rejections

### LINKED ISSUE #199: Provide reasoning on rejection
When a portfolio manager reject a field partner's document, the field partner gets a notification that the document has been rejected. However, it may not be clear what was wrong with the document unless the portfolio manager informs the field partner through email or some other service, negating the purpose of this app. We want to provide a way for field partners to see why their documents were rejected inside of the application.

### PR DESCRIPTION
**Pull request by arpanlaha**
Resolves #199

### CODE REVIEW

File: frontend/src/components/DocumentPreview.js [hunk 1]
```diff
@@ -43,10 +43,14 @@ export class DocumentPreview extends Component {
     super(props)
 
     this.state = {
-      accessToken: null
+      modal: false,
```
Comment (arpanlaha) [inline frontend/src/components/DocumentPreview.js]: modal never was initialized before but since null is false i guess it worked out

File: frontend/src/utils/ApiWrapper.js [hunk 2]
```diff
@@ -914,7 +913,9 @@ export const updateDocumentStatus = (userID, id, status) => {
       }
     })
     .then(response => {
-      createMessage(userID, false, true, id)
+      reason
```
Comment (chyku) [inline frontend/src/utils/ApiWrapper.js]: Do you still need to check for reason existing here if you also check it in line 1092

File: backend/api/views/message.py [hunk 3]
```diff
@@ -108,6 +108,12 @@ def add_message():
         f"Your Field Partner from {organization} has uploaded a document for {docclass_name}.",  # organization, document class name
     ]
 
+    if "reason" in data:
+        reason = data.get("reason")
+        contents[
+            1
```
Comment (rgychiu) [inline backend/api/views/message.py]: Does this actually look like this in the code bc if so this is weirdest post-lint format thing I've seen

File: frontend/src/utils/ApiWrapper.js (hunk 2 above)
Comment (rgychiu) [reply frontend/src/utils/ApiWrapper.js]: +1

File: frontend/src/components/DocumentPreview.js [hunk 4]
```diff
@@ -136,6 +172,23 @@ export class DocumentPreview extends Component {
 
     return (
       <>
+        <Modal isOpen={this.state.rejectModal} toggle={this.rejectToggle}>
+          <ModalHeader>{text.rejectInstructions}</ModalHeader>
+          <ModalBody>
+            <Input
+              type="textarea"
+              className="textarea-input"
+              style={{ height: '200px' }}
```
[the remark this answers is not in the document]
Comment (rgychiu) [reply frontend/src/components/DocumentPreview.js]: +1, if other have a textarea input element and have this height we should put this style into index.scss and then use the className, but if this is the only one then I don't really see too much an issue with leaving it in despite my hatred for inline styling, it'll either add 3 lines in a css file or be inline styling so pick your poison

**Comment by rgychiu** [comment]
CSS fixed in #206
